name: Github publish
on:
  push:
    branches: [develop]
jobs:
  get-markdown:
    name: Get markdown file
    runs-on: windows-latest
    steps:
    - name: checkout file
      env:
        ACCESS_TOKEN: ${{secrets.HOME_ACTIONS_SECRET}}
        TIMESAMP:
      run:
        git clone https://github.com/StrugglingBirds/home.git -b develop
    - name: install
      run: cd home && yarn install
    - name: build
      run: cd home && yarn run build
    - name: git config email
      run: cd home && git config --global user.email "shiyanggreat@163.com"
    - name: git config username
      run: cd home && git config --global user.name "StrugglingBirds"
    - name: git publish
      run: cd home && git add . && git commit -m '部署date' && git push
