name: Github publish
on:
  push:
    branches: [develop]
jobs:
  get-markdown:
    name: Get markdown file
    runs-on: ubuntu-latest
    steps:
    - name: checkout file
      env:
        ACCESS_TOKEN: ${{secrets.HOME_ACTIONS_SECRET}}
        TIMESAMP: ${date}
      run:
        git clone https://github.com/StrugglingBirds/home.git -b develop
    - name: install
      run: cd home && yarn install
    - name: build
      run: cd home && yarn run build
    - name: git config
      run: cd home && git config --global user.email "shiyanggreat@163.com" && git config --global user.name "StrugglingBirds"
    - name: branch switch main
      run: cd home && git checkout -b main && git branch --set-upstream-to=origin/main
    - name: git commit
      run: cd home && git add . && git commit -m '部署'
    - name: git remote
      run: cd home && git remote set-url origin "https://StrugglingBirds:github1235813@github.com/StrugglingBirds/home.git"
    - name: git rebase
      run: cd home && git rebase
    - name: show git config
      run: cd home && git config -l
    - name: git push
      run: cd home && git push origin main
