name: Github publish
on:
  push:
    branches: [main, develop]
jobs:
  get-markdown:
    name: Get markdown file
    runs-on: ubuntu-latest
    steps:
    # - name: checkout file
    #   env:
    #     ACCESS_TOKEN: ${{secrets.HOME_TOKEN}}
    #     TIMESAMP: ${date}
    #   run:
    #     git clone https://github.com/StrugglingBirds/home.git -b develop
    # - name: install
    #   run: cd home && yarn install
    # - name: build
    #   run: cd home && yarn run build
    - name: checkout
      uses: actions/checkout@master
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with: 
        ACCESS_TOKEN: ${{ secrets.HOME_TOKEN }}
        BRANCH: main
        FOLDER: docs
        BUILD_SCRIPT: yarn install && yarn run build
    # - name: git config
    #   run: cd home && git config --global user.email "shiyanggreat@163.com" && git config --global user.name "StrugglingBirds"
    # - name: branch switch main
    #   run: cd home && git checkout -b main && git branch --set-upstream-to=origin/main
    # - name: git commit
    #   run: cd home && git add . && git commit -m '部署'
    # - name: git remote
    #   run: cd home && git remote set-url origin "https://$ACCESS_TOKEN@github.com/StrugglingBirds/home.git"
    # - name: git rebase
    #   run: cd home && git rebase
    # - name: show git config
    #   run: cd home && git config -l
    # - name: git push
    #   run: cd home && git push origin main
